---
kind: pipeline
type: kubernetes
name: deploy
trigger:
  event:
    - promote

steps:
  - name: fetch and checkout
    image: alpine/git
    commands:
      - git fetch --tags
      - git checkout $${VERSION}

  - name: deploy to cs-qa
    image: quay.io/ukhomeofficedigital/kd
    commands:
      - cd kube
      - ./deploy.sh
    environment:
      ENVIRONMENT: cs-qa
      KUBE_TOKEN:
        from_secret: hocs_case_creator_cs_qa
      KUBE_SERVER: https://kube-api-notprod.notprod.acp.homeoffice.gov.uk
      CLUSTER_NAME: acp-notprod
    when:
      target:
        - release
    depends_on:
      - fetch and checkout

  - name: deploy to not prod
    image: quay.io/ukhomeofficedigital/kd
    commands:
      - cd kube
      - ./deploy.sh
    environment:
      ENVIRONMENT: ${DRONE_DEPLOY_TO}
      KUBE_TOKEN:
        from_secret: hocs_case_creator_${DRONE_DEPLOY_TO/-/_}
      KUBE_SERVER: https://kube-api-notprod.notprod.acp.homeoffice.gov.uk
      CLUSTER_NAME: acp-notprod
    depends_on:
      - fetch and checkout
    when:
      target:
        exclude:
          - release
          - "*-prod"

  - name: deploy to prod
    image: quay.io/ukhomeofficedigital/kd
    commands:
      - cd kube
      - ./deploy.sh
    environment:
      ENVIRONMENT: ${DRONE_DEPLOY_TO}
      KUBE_TOKEN:
        from_secret: hocs_case_creator_${DRONE_DEPLOY_TO/-/_}
      KUBE_SERVER: https://kube-api-prod.prod.acp.homeoffice.gov.uk
      CLUSTER_NAME: acp-prod
    depends_on:
      - fetch and checkout
    when:
      target:
        include:
          - "*-prod"
---
kind: pipeline
type: kubernetes
name: deploy tag
trigger:
  event:
    - tag
  branch:
    - main

steps:
  - name: deploy to cs-dev
    image: quay.io/ukhomeofficedigital/kd
    commands:
      - cd kube
      - ./deploy.sh
    environment:
      ENVIRONMENT: cs-dev
      KUBE_TOKEN:
        from_secret: hocs_case_creator_cs_dev
      KUBE_SERVER: https://kube-api-notprod.notprod.acp.homeoffice.gov.uk
      CLUSTER_NAME: acp-notprod
      VERSION: "${DRONE_TAG}"
    depends_on:
      - clone

  - name: deploy migrator to cs-dev
    image: quay.io/ukhomeofficedigital/kd
    commands:
      - cd kube
      - ./deploy.sh
    environment:
      ENVIRONMENT: cs-dev
      DEPLOYMENT_TYPE: migrator
      SQS_SECRET_NAME: case-migrator-sqs
      KUBE_TOKEN:
        from_secret: hocs_case_creator_cs_dev
      KUBE_SERVER: https://kube-api-notprod.notprod.acp.homeoffice.gov.uk
      CLUSTER_NAME: acp-notprod
      VERSION: "${DRONE_TAG}"
    depends_on:
      - clone
