version: '3.8'

services:

  localstack:
    image: localstack/localstack:0.11.1
    ports:
      - 4566:4566
    networks:
      - hocs-network
    environment:
      HOSTNAME_EXTERNAL: localstack
      DEFAULT_REGION: eu-west-2
      SERVICES: sqs,sns,s3
    volumes:
      - ./config/localstack:/docker-entrypoint-initaws.d

networks:
  hocs-network:
