info:
  app:
    name: ${name:hocs-case-creator}
    fullname: HOCS Case Creator
    version: ${version:0.0.1}

spring:
  main:
    banner-mode: off

server:
  port: 8092
  shutdown: graceful

camel:
  springboot:
    main-run-controller: false

aws:
  sqs:
    config:
      region: eu-west-2
    ukvi-complaint:
      url:
      account:
        access-key:
        secret-key:
      attributes:
        max-messages: 10
        wait-time: 20
  sns:
    config:
      region: eu-west-2
    audit:
      account:
        access-key:
        secret-key:
        id:
      topic-name:
      arn: arn:aws:sns:${aws.sns.config.region}:${aws.sns.audit.account}:${aws.sns.audit.topic-name}

case:
  creator:
    basicauth: UNSET
    case-service: http://localhost:8082
    ukvi-complaint:
      group: /COMP_CCH_zqxmzQ6iEkTRw
      team: 08e30ffc-2087-ff3a-b19b-343a88491347
      user: 22ca514d-c205-47a0-9e38-68daee4c1299
    workflow-service: http://localhost:8091

audit:
  namespace: local

document:
  s3:
    access-key: 12345
    secret-key: 12345
    untrusted-bucket-name: untrusted-bucket
    untrusted-bucket-kms-key:

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
      probes:
        enabled: true
