localstack:
  base-url: http://${localstack.config.host}:${localstack.config.port}
  config:
    host: localhost
    port: 4566
    region: eu-west-2

aws:
  sqs:
    queue:
      url: ${localstack.base-url}/queue/case-creator-queue
      account:
        access-key: 12345
        secret-key: 12345
      attributes:
        max-messages: 1
        wait-time: 5

  s3:
    config:
      region: eu-west-2
    untrusted:
      account:
        access-key: 12345
        secret-key: 12345
        bucket-kms-key:
      bucket-name: untrusted-bucket

case:
  creator:
    case-service: http://localhost:8082
    workflow-service: http://localhost:8091
    document-service: http://localhost:8083
    info-service: http://localhost:8085
---
spring:
  config:
    activate:
      on-profile: ukvi
case:
  creator:
    identity:
      group: /TEST_TEAM_GROUP
      team: 00000000-0000-0000-0000-000000000002
      user: 00000000-0000-0000-0000-000000000003
---
spring:
  config:
    activate:
      on-profile: migration
case:
  creator:
    identity:
      group: /evPR7Fa9S063C6SLsHkNaw
      team:
      user: 428804f0-bc6a-45b2-9dad-a73378606b01
    migration:
      parent-topic-uuid: 'eb939efd-8aa8-46e0-a9c3-9ae979e151ab'
aws:
  sqs:
    queue:
      url: ${localstack.base-url}/queue/migration-queue
