info:
  app:
    name: ${name:hocs-case-creator}
    fullname: HOCS Case Creator
  namespace: local

server:
  http2:
    enabled: true
  port: 8092
  shutdown: graceful

spring:
  main:
    banner-mode: off
    web-application-type: none
  flyway:
    locations: classpath:/db/migration/postgresql
    schema: ${db.schema.name:message_log}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${db.host:localhost}:${db.port:5432}/${db.name:postgres}?currentSchema=${db.schema.name:message_log}&user=${db.username:root}&password=${db.password:dev}&stringtype=unspecified

aws:
  sqs:
    config:
      region: eu-west-2
    case-creator:
      url:
      account:
        access-key:
        secret-key:
      attributes:
        max-messages: 10
  s3:
    config:
      region: eu-west-2
    untrusted:
      account:
        access-key:
        secret-key:
        bucket-kms-key:
      bucket-name:

case:
  creator:
    case-service: http://localhost:8082
    identities:
      complaints:
        ukvi:
          group:
          team:
          user:
      migration:
        group: 85eecc42-cbfb-4352-ac4d-67f269346a67
        team: d3c3cc3a-21e1-48b4-9268-7d5f66ac1dd9
        user: 9f69d980-258b-448c-a958-199a698dfd44
    workflow-service: http://localhost:8091

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
      probes:
        enabled: true

message:
  ignored-types:
