info:
  app:
    name: ${name:hocs-case-creator}
    fullname: HOCS Case Creator
  namespace: local

server:
  http2:
    enabled: true
  port: 8092
  shutdown: graceful

spring:
  main:
    banner-mode: off
  flyway:
    locations: classpath:/db/migration/postgresql
    schemas: ${db.schema.name:case_creator}
  datasource:
    url: jdbc:postgresql://${db.host:localhost}:${db.port:5432}/${db.name:postgres}?currentSchema=${db.schema.name:case_creator}&user=${db.username:root}&password=${db.password:dev}&stringtype=unspecified
  jpa:
    database: postgresql
    open-in-view: false

aws:
  sqs:
    config:
      region: eu-west-2
    case-creator:
      url:
      account:
        access-key:
        secret-key:
      attributes:
        max-messages: 10
  s3:
    config:
      region: eu-west-2
    untrusted:
      account:
        access-key:
        secret-key:
        bucket-kms-key:
      bucket-name:

case:
  creator:
    case-service: http://localhost:8082
    identities:
      complaints:
        ukvi:
          group:
          team:
          user:
      migration:
        group:
        team:
        user:
    workflow-service: http://localhost:8091

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
      probes:
        enabled: true

message:
  ignored-types:
