localstack:
  base-url: http://${localstack.config.host}:${localstack.config.port}
  config:
    host: localhost
    port: 4566
    region: eu-west-2

aws:
  sqs:
    case-creator:
      url: ${localstack.base-url}/queue/ukvi-complaint-queue
      account:
        access-key: 12345
        secret-key: 12345
      attributes:
        max-messages: 1
        wait-time: 5
    case-migrator:
      url: ${localstack.base-url}/queue/migration-queue

  s3:
    config:
      region: eu-west-2
    untrusted:
      account:
        access-key: 12345
        secret-key: 12345
        bucket-kms-key:
      bucket-name: untrusted-bucket

  case:
    creator:
      case-service: http://localhost:8082
      identities:
        complaints:
          ukvi:
            group:
            team:
            user:
        migration:
          group:
          team:
          user:
      workflow-service: http://localhost:8091

spring:
  flyway:
    locations: classpath:/db/migration/postgresql
    schema: ${db.schema.name:message_log}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.PostgreSQLDialect
  main:
    web-application-type: none
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${db.host:localhost}:${db.port:5432}/${db.name:postgres}?currentSchema=${db.schema.name:message_log}&user=${db.username:}&password=${db.password:}&stringtype=unspecified
    message_log:
      driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
      url: jdbc:sqlserver://${db.host:localhost}:${db.port:5434};databaseName=message_log
      username: ${db.username:}
      password: ${db.password:}