localstack:
  base-url: http://${localstack.config.host}:${localstack.config.port}
  config:
    host: localhost
    port: 4566
    region: eu-west-2

aws:
  sqs:
    case-creator:
      url: ${localstack.base-url}/queue/ukvi-complaint-queue
      account:
        access-key: 12345
        secret-key: 12345
      attributes:
        max-messages: 1
        wait-time: 5
  s3:
    config:
      region: eu-west-2
    untrusted:
      account:
        access-key: 12345
        secret-key: 12345
        bucket-kms-key:
      bucket-name: untrusted-bucket
