info:
  app:
    name: ${name:hocs-case-creator}
    fullname: HOCS Case Creator
    version: ${version:0.0.1}
  namespace: local

spring:
  main:
    banner-mode: off

server:
  port: 8092
  shutdown: graceful

messages:
  ignored-types:

aws:
  sqs:
    config:
      region: eu-west-2
    ukvi-complaint:
      url:
      account:
        access-key:
        secret-key:
      attributes:
        max-messages: 10
  s3:
    config:
      region: eu-west-2
    untrusted:
      account:
        access-key:
        secret-key:
        bucket-kms-key:
      bucket-name:

case:
  creator:
    basicauth: UNSET
    case-service: http://localhost:8082
    ukvi-complaint:
      group: /COMP_CCH_zqxmzQ6iEkTRw
      team: 08e30ffc-2087-ff3a-b19b-343a88491347
      user: 22ca514d-c205-47a0-9e38-68daee4c1299
    workflow-service: http://localhost:8091

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
      probes:
        enabled: true
