package uk.gov.digital.ho.hocs.domain.repositories.entities;

public enum Status {
    CASE_CORRESPONDENTS_FAILED,
    CASE_CORRESPONDENTS_HANDLED,
    CASE_ADDITIONAL_CORRESPONDENTS_FAILED,
    CASE_CREATED,
    CASE_CREATION_FAILED,
    CASE_DOCUMENT_CREATED,
    CASE_DOCUMENT_FAILED,
    CASE_MIGRATION_FAILED,
    CASE_STAGE_RETRIEVAL_FAILED,
    CASE_STAGE_RETRIEVED,
    CASE_TEAM_UPDATED,
    CASE_TEAM_UPDATE_FAILED,
    CASE_USER_UPDATED,
    CASE_USER_UPDATE_FAILED,
    WORKFLOW_MIGRATION_FAILURE,
    COMPLETED,
    IGNORED,
    MESSAGE_PARSE_FAILURE,
    MESSAGE_TYPE_INVALID,
    MESSAGE_VALIDATION_FAILED,
    MESSAGE_VALIDATION_SUCCESS,
    PENDING,
    DUPLICATE_MIGRATED_REFERENCE
}
