---
hocs-generic-service:

  deployment:
    annotations:
      downscaler/downtime: "Sat-Sun 00:00-24:00 Europe/London,Mon-Fri 00:00-08:10 Europe/London,Mon-Fri 17:50-24:00 Europe/London"

  app:
    resources:
      limits:
        memory: 512Mi
      requests:
        memory: 512Mi
